name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and analyze on SonarCloud
        # Ajuste o diretório de trabalho para a pasta do backend
        working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify -Dspring.profiles.active=test \
            -Dsonar.projectKey=ES-Project-2024-2_Gestao-de-gastos-pessoais \
            -Dsonar.organization=es-project-2024-2 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
